# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install, lint and build project
        run: make build
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Archive dist
          path: dist
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: dist
          commit_message: "Deploy to GitHubPages"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}